av1shek/All-Coding-Platform-Solutions

- LeetCode/42 Trapping Rain Water.cpp
I have added Leetcode question 42 solution  "Trapping Rain Water"
> Trapping Rain Water

- LeetCode/200 Number of Islands.cpp
I have added Leetcode question 200 solution  "Number of Islands"
> Number of Islands

- LeetCode/123 Best Time to Buy and Sell Stock III.cpp
I have added Leetcode question 123 solution  " Best Time to Buy and Sell Stock III"
>  Best Time to Buy and Sell Stock III

- LeetCode/15 3Sum.cpp
Solution of 3Sum problem
Related Issue: #9
> 3sum added

- LeetCode/70. Climbing Stairs.cpp
> Climbing Stairs added

- README.md
Updated the readme file with Hactoberfest 2022.
> Made changes to README.md

- README.md
Changed hactober badge from 2021 to 2022.
> Changed hactober badge from 2021 to 2022

- LeetCode/Increasing Triplet Subsequence.cpp
- LeetCode/Shortest Bridge.cpp
leetcode problem increasing triplet subsequence using LIS concept
> added increasing triplet subsequence

- CodeChef/CARVANS.cpp
Added CARVANS.cpp (CodeChef/CARVANS.cpp)
Question Link: https://www.codechef.com/submit/CARVANS
> Added CARVANS.cpp

- InterviewBit/First_missing_positive.cpp
added first missing positive in interview directory.
> first missing positive

- CodeChef/BUILDINGRACE.cpp
- CodeChef/TWODIFFPALIN.cpp
Label : Hacktoberfest2022
Hacktoberfest-accepted
> Updated codechef : Added solution for Building Race Problem

- Codeforces/1698C 3Sum Closure.cpp
added C++ code of above problem
> 1698C  Sum closure

- LeetCode/31. Next Permutation.cpp
added Next Permutation cpp file. Please review it and merge it
> added Next Permutation

- LeetCode/5. Longest Palindromic Substring.cpp
Please mark it as Hactoberfest accepted
> Create 5. Longest Palindromic Substring.cpp

- LeetCode/32 Longest Valid Parentheses.cpp
added C++ code of above problem
> Create 32 Longest Valid Parentheses.cpp

- LeetCode/Java/RecoverBinarySearchTree_Probelm_99.java
This is the solution code for
Leetcode Problem 99.
Problem Link- https://leetcode.com/problems/recover-binary-search-tree/
Problem Description- 
You are given the root of a binary search tree (BST), where the values of exactly two nodes of the tree were swapped by mistake. Recover the tree without changing its structure.
> Solution code for Leetcode Problem 99 Recover Binary Search Tree

- LeetCode/Java/RestoreIPAddress93.java
A valid IP address consists of exactly four integers separated by single dots. Each integer is between 0 and 255 (inclusive) and cannot have leading zeros.
Given a string s containing only digits, return all possible valid IP addresses that can be formed by inserting dots into s. You are not allowed to reorder or remove any digits in s. You may return the valid IP addresses in any order.
> Restore IP Address problem 93 from Leetcode

- LeetCode/Java/LetterCombinationOfPhoneNumber_Problem_17.java
Letter Combinations of a Phone Number solution code
Problem Link- https://leetcode.com/problems/letter-combinations-of-a-phone-number/
Problem Description-
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.
A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.
> Solution Code for Leetcode Problem Letter Combinations of a Phone Number

- LeetCode/Java/GasStation134.java
There are n gas stations along a circular route, where the amount of gas at the ith station is gas[i].
You have a car with an unlimited gas tank and it costs cost[i] of gas to travel from the ith station to its next (i + 1)th station. You begin the journey with an empty tank at one of the gas stations.
Given two integer arrays gas and cost, return the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return -1. If there exists a solution, it is guaranteed to be unique
> LeetCode Problem 134

- LeetCode/712. Minimum ASCII Delete Sum for Two Strings
> 712. Minimum ASCII Delete Sum for Two Strings

- LeetCode/Java/IPO_502.java
Suppose LeetCode will start its IPO soon. In order to sell a good price of its shares to Venture Capital, LeetCode would like to work on some projects to increase its capital before the IPO. Since it has limited resources, it can only finish at most k distinct projects before the IPO. Help LeetCode design the best way to maximize its total capital after finishing at most k distinct projects.
You are given n projects where the ith project has a pure profit profits[i] and a minimum capital of capital[i] is needed to start it.
Initially, you have w capital. When you finish a project, you will obtain its pure profit and the profit will be added to your total capital.
Pick a list of at most k distinct projects from given projects to maximize your final capital, and return the final maximized …
> Leetcode problem 502 based on greedy approach

- LeetCode/Java/ValidSudoku_36.java
Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:
Each row must contain the digits 1-9 without repetition. Each column must contain the digits 1-9 without repetition. Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.
> Leetcode problem 36 Valid Sudoku

- CodeChef/biryani classes codechef
codechef program for biryani classes
> biryani classes program

- LeetCode/Rotate Image.cpp
48.  well written code for rotate image problem
https://leetcode.com/problems/rotate-image/
> create Rotate Image.cpp

- CodeChef/EVMHACK@codechef.cpp
This is a CPP code regarding EVMhack of CODECHEF.
> EVMHACK@codechef.CPP

- LeetCode/17 Letter Combinations of a Phone Number.cpp
created a file solving the leetcode problem 17. Letter combinations of a phone number
> added leetcode problem 17

- LeetCode/Java/HouseRobber2.java
You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Meanwhile, adjacent houses have a security system connected, and it will automatically contact the police if two adjacent houses were broken into on the same night.
Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.
> HouseRobber 2 LeetCode problem 213

- LeetCode/Java/PalindromePartitioning_Problem_131.java
- LeetCode/Java/WiggleSequence_Problem376.java
Problem Link- https://leetcode.com/problems/palindrome-partitioning/
Problem Description-
Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.
A palindrome string is a string that reads the same backward as forward.
> Palindrome partitioning (Problem 131 - Leetcode)

- LeetCode/Java/WiggleSequence_Problem376.java
The solution code for the Problem 376 Wiggle Sequence is added.
Problem Link- https://leetcode.com/problems/wiggle-subsequence/
Problem Statement-
A wiggle sequence is a sequence where the differences between successive numbers strictly alternate between positive and negative. The first difference (if one exists) may be either positive or negative. A sequence with one element and a sequence with two non-equal elements are trivially wiggle sequences.
For example, [1, 7, 4, 9, 2, 5] is a wiggle sequence because the differences (6, -3, 5, -7, 3) alternate between positive and negative.
In contrast, [1, 4, 7, 2, 5] and [1, 7, 4, 5, 5] are not wiggle sequences. The first is not because its first two differences are positive, and the second is not because its last difference is zero.
> Problem 376 Wiggle Sequence

- LeetCode/1664. Ways to Make a Fair Array
prefix sum suffix sum approach
> 1664. Ways to Make a Fair Array

- LeetCode/Russian-Doll-Envelopes.cpp
Attaching A.C. code for the problem mentioned.
> Added Russian Doll Envopes Question (Leetcode)

- factorialUsingRecursion.java
gfg problem i hope you will accept it
> factorialUsingRecursion

- RemoveElement.cpp
i hope you will accept my request 
thank you
> 27. Remove Element

- Google Kickstart 2022 Round G Walktober.py
I am requesting you to merge my PR for adding the solution to Google's Kicstart 2022 Round G Problem 1: Walktober.
I implemented the solution in python, and got a successful submission.
> Create Google Kickstart 2022 Round G Walktober.py

- CodeChef/MANIPULATE
https://www.codechef.com/submit/MANIPULATE
QUESTION LINK 
SOLUTION IN C++ IS ADDED
> SOLUTION OF THE QUESTION MANIPULATE IN CODECHEF

- LeetCode/234 Palindrome Linked List.cpp
I have added Leetcode solution of "234. Palindrome Linked List" in C++ Language.
> added Palindrome Linked List leetcode

- LeetCode/1_Two_Sum.cpp
- LeetCode/2_Remove_Duplicates_from_Sorted_Array.cpp
- LeetCode/3_Remove_Element.cpp
- LeetCode/4_Search_Insert_Position.cpp
- LeetCode/5_Plus_One.cpp
- LeetCode/6_Container_With_Most_Water.cpp
Hello, I have added a few leetcode problems. Please merge. thank you.
> Added Two Sum code LeetCode

- Codeforces/1742A_Sum.c
> Add solution for 1742A_Sum

- 581 Shortest Unsorted Continuous Subarray.java
- LeetCode/Java/581 Shortest Unsorted Continuous Subarray.java
Successfully added Shortest Unsorted Continuous Subarray using Java. 
Issue No. #214 
Kindly review and merge the PR.
Thanks
> 581 Shortest Unsorted Continuous Subarray.java

- CodeChef/CNOTE.cpp
- LeetCode/881 boats-to-save-people.cpp
Added boats to save people code
> Create 881 boats-to-save-people.cpp

- InterviewBit/Best Time to Buy and Sell Stocks I
This question was asked in amazon and facebook. 
https://www.interviewbit.com/problems/best-time-to-buy-and-sell-stocks-i/
Solution is uploaded in CPP and Python
> Best Time to Buy and Sell Stocks I

- CodeChef/minimiseLCS.cpp
codechef MINLCS problem solution
> probnlem code : MINLCS

- Binary Tree Level Order Traversal (Leetcode-102)
- LeetCode/102. Binary Tree Level Order Traversal
Successfully added Binary Tree Level Order Traversal using C++.
Issue no. #177 
Kindly review and merge the PR.
Thanks.
> Added Binary Tree Level Order Traversal (Leetcode-102)

- Codeforces/twosets.cpp
- Codeforces/weirdalgo.cpp
It is a solution of two sets probelm of cses probelm set of codeforces.
> Twosets shekhar

- CodeChef/Prim.cpp
- CodeChef/trailingzero.cpp
- LeetCode/Permutations-II.java
trailing zero problem in factorail in c++
> Jdavy123trailing

- LeetCode/Number of Steps to Reduce a Number to Zero.cpp
- Number of Steps to Reduce_a_Number_to_Zero.md
PLease add Hacktoberfest_accepted label to my Pull request
> Number_of_Steps_to_Reduce_a_Number_to_Zero_added

- LeetCode/Java/KthSmallestElementBST.java
Problem Statement :-  Kth Smallest Element in a BST
Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.
> Kth Smallest Element in a BST

- LeetCode/nQueen.java
Efficient code for  N Queen Backtracking Problem
> Added code for N Queen Backtracking Problem

- Codeforces/1287A_Angry_Students.cpp
added the solution of this question because it is good implementation of greedy approach.
> added solution of codeforce problem 1287A

- Codeforces/Amr_and_Pins.cpp
- Codeforces/DZY_loves_strings.cpp
- Codeforces/Fedor_and_New_Game.cpp
- Codeforces/Jzzuh_and_Sequence.cpp
- Codeforces/Queue_At_the_School.cpp
- Codeforces/Random_Teams.cpp
- Codeforces/Xenia_and_Ringroad.cpp
Please add a Hactober-accepted tag
> Added 7 B Codeforces Solutions

- LeetCode/Find Peak Element.cpp
- LeetCode/Maximum Depth of Binary Tree.cpp
Hello, @av1shek I have successfully added the code for Maximum Depth of Binary Tree using C++.
Issue no. #212 
Kindly review and merge the PR.
Thanks
> Added Maximum Depth of Binary Tree using C++

- LeetCode/Evaluate_Divison.cpp
Added AC code with comments for Evaluate Division problem LC.
> Added Evaluate Division | LC | Union Find

- LeetCode/valid_sudoku.cpp
Added AC code for Valid Sudoku Problem LC
> Added Valid Sudoku problem LC

- LeetCode/skyline_problem.cpp
Added AC code for The_Skyline_Problem ( LC HARD )
> Added The_Skyline_Problem LC

- LeetCode/course_schedule_2.cpp
Added AC code for Course Schedule 2 problem ( Leetcode )
> Added Course Schedule-2 problem LC

- Range_Sum_Query.cpp
Added AC code for Range Sum Query ( BIT based problem ) available on Leetcode.
> Added Range Sum Query Problem | BIT

- traveling_salesman.py
> added traveling salesman
